version: '3.8'

services:
  # Web server (Nginx)
  web:
    image: nginx:alpine
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www:ro
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php-fpm
    restart: unless-stopped

  # PHP-FPM service
  php-fpm:
    image: php:8.3-fpm
    volumes:
      - ./:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://192.168.0.118:8085
    depends_on:
      - db
      - setup
    restart: unless-stopped

  # Setup service for Composer and Laravel setup
  setup:
    image: composer:2
    working_dir: /var/www
    command: >-
      sh -c "composer install --no-dev --prefer-dist --no-progress --optimize-autoloader
      && [ -f .env ] || cp .env.example .env
      && php artisan key:generate --force"
    volumes:
      - ./:/var/www
    restart: "no"

  # MySQL database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8084:80"
    depends_on:
      - db
    restart: unless-stopped
 

volumes:
  dbdata:



