

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:local
    container_name: laravel_app
    working_dir: /var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://localhost:8085
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - ./:/var/www/html
    depends_on:
      - setup
      - db
    networks:
      - traefik_net
      - rede_microservicos

  web:
    image: nginx:stable-alpine
    container_name: laravel_web
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - traefik_net
      - rede_microservicos

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - traefik_net
      - rede_microservicos

  phpmyadmin:
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8084:80"
    depends_on:
      - db
    networks:
      - traefik_net
      - rede_microservicos

  setup:
    image: composer:2
    container_name: laravel_setup
    working_dir: /var/www/html
    command: >-
      sh -lc "composer install --no-dev --prefer-dist --no-progress --optimize-autoloader
      && php -r 'file_exists(".env") || copy(".env.example", ".env");'
      && php artisan key:generate --force
      "
    volumes:
      - ./:/var/www/html
    networks:
      - traefik_net
      - rede_microservicos
    restart: "no"

volumes:
  dbdata:

networks:
  rede_microservicos:
    external: true
  traefik_net:
    # criado pelo compose desta stack (não externo)
    external: false



