version: '3.8'

services:
  # Serviço que prepara o código (Composer e APP_KEY)
  setup:
    image: composer:2
    working_dir: /app
    command: >-
      sh -lc "composer install --no-dev --prefer-dist --no-progress --optimize-autoloader
      && [ -f .env ] || cp .env.example .env
      && php artisan key:generate --force"
    volumes:
      - ./:/app
    restart: "no"

  # App com Nginx + PHP-FPM em um único container (sem build)
  app:
    image: webdevops/php-nginx:8.3
    depends_on:
      - setup
      - db
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://localhost:8085
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - ./:/app
    ports:
      - "8085:80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8084:80"
    depends_on:
      - db

volumes:
  dbdata:



